/**
 * Utility: Firestore database operations
 */
import {
  collection,
  query,
  where,
  getDocs,
  addDoc,
  Timestamp,
} from 'firebase/firestore'
import { db } from '../config/firebase'

/**
 * Verify if HUID code exists in Firestore
 * @param {string} huidCode - The HUID code to verify
 * @returns {Promise<Object>} Verification result with details
 */
export const verifyHUID = async (huidCode) => {
  try {
    const huidsRef = collection(db, 'huid_codes')
    const q = query(huidsRef, where('code', '==', huidCode.toUpperCase()))
    const querySnapshot = await getDocs(q)

    if (querySnapshot.empty) {
      return {
        isValid: false,
        message: 'No hallmark found for this HUID code.',
      }
    }

    const huidData = querySnapshot.docs[0].data()
    return {
      isValid: huidData.valid || false,
      shop: huidData.shop || 'Unknown',
      city: huidData.city || 'Unknown',
      message: huidData.valid
        ? '✅ Verified BIS Hallmark'
        : '❌ Invalid or Fake Jewellery',
    }
  } catch (error) {
    console.error('Error verifying HUID:', error)
    return {
      isValid: false,
      message: 'Error connecting to database. Please try again.',
    }
  }
}

/**
 * Save complaint to Firestore
 * @param {Object} complaintData - Complaint information
 * @returns {Promise<string>} Document ID of saved complaint
 */
export const saveComplaint = async (complaintData) => {
  try {
    const complaintsRef = collection(db, 'complaints')
    const docRef = await addDoc(complaintsRef, {
      ...complaintData,
      createdAt: Timestamp.now(),
      status: 'pending',
    })
    return docRef.id
  } catch (error) {
    console.error('Error saving complaint:', error)
    throw error
  }
}

/**
 * Generate formatted complaint letter text
 */
export const generateComplaintLetter = (formData) => {
  const today = new Date().toLocaleDateString('en-IN')

  return `
========================
FORMAL COMPLAINT LETTER
========================

Date: ${today}

To,
Bureau of Indian Standards (BIS)
New Delhi, India

Subject: Consumer Complaint against Gold Jewellery Purchase

Dear Sir/Madam,

I am writing to lodge a formal complaint regarding a fraudulent or unfair gold jewellery transaction.

---
COMPLAINANT DETAILS:
---
Name: ${formData.customerName}
City: ${formData.city}
Date of Complaint: ${today}

---
RETAILER DETAILS:
---
Shop Name: ${formData.shopName}
Location: ${formData.city}

---
ISSUE DESCRIPTION:
---
${formData.issueDescription}

---
REQUESTED ACTION:
---
• Investigation into the jewellery for proper hallmark verification
• Refund or replacement if fraud is confirmed
• Action against fraudulent retailer

I request immediate intervention and a fair resolution within 30 days.

---
DECLARATION:
---
I hereby declare that the information provided above is true and correct to the best of my knowledge. I am seeking protection as a consumer under the Consumer Protection Act.

Yours faithfully,

${formData.customerName}

---
Generated by Gold Guardian - BIS Consumer Protection Platform
`
}
